# data.py
# Define here your lists of stations, correspondences, and exception rules

# Helper to normalize station names for exception keys
def normalize(name):
    """Remove dashes and spaces, uppercase"""
    return name.replace('-', '').replace(' ', '').upper()


# Stations per line
LISTAS = {
            "Línea 1": ["1-PINAR DE CHAMARTIN", "1-BAMBU", "1-CHAMARTIN", "1-PLAZA DE CASTILLA", "1-VALDEACEDERAS", "1-TETUAN", "1-ESTRECHO", "1-ALVARADO", "1-CUATRO CAMINOS", "1-RIOS ROSAS", "1-IGLESIA", "1-BILBAO", "1-TRIBUNAL", "1-GRAN VIA", "1-SOL", "1-TIRSO DE MOLINA", "1-ANTON MARTIN", "1-ESTACION DEL ARTE", "1-ATOCHA RENFE", "1-MENENDEZ PELAYO", "1-PACIFICO", "1-PUENTE DE VALLECAS", "1-NUEVA NUMANCIA", "1-PORTAZGO", "1-BUENOS AIRES", "1-ALTO DEL ARENAL", "1-MIGUEL HERNANDEZ", "1-SIERRA DE GUADALUPE", "1-VILLA DE VALLECAS", "1-CONGOSTO", "1-LA GAVIA", "1-LAS SUERTES", "1-VALDECARROS"],
            "Línea 2": ["2-LAS ROSAS", "2-AVENIDA DE GUADALAJARA", "2-ALSACIA", "2-LA ALMUDENA", "2-LA ELIPA", "2-VENTAS", "2-MANUEL BECERRA", "2-GOYA", "2-PRINCIPE DE VERGARA", "2-RETIRO", "2-BANCO DE ESPAÑA", "2-SEVILLA", "2-SOL", "2-OPERA", "2-SANTO DOMINGO", "2-NOVICIADO", "2-SAN BERNARDO", "2-QUEVEDO", "2-CANAL", "2-CUATRO CAMINOS"],
            "Línea 3": ["3-MONCLOA", "3-ARGUELLES", "3-VENTURA RODRIGUEZ", "3-PLAZA ESPAÑA", "3-CALLAO", "3-SOL", "3-LAVAPIES", "3-EMBAJADORES", "3-PALOS DE LA FRONTERA", "3-DELICIAS", "3-LEGAZPI", "3-ALMENDRALES", "3-HOSPITAL DOCE DE OCTUBRE", "3-SAN FERMIN-ORCASUR", "3-CIUDAD DE LOS ANGELES", "3-VILLAVERDE BAJO-CRUCE", "3-SAN CRISTOBAL", "3-VILLAVERDE ALTO", "3-EL CASAR"],
            "Línea 4": [
                "4-ARGUELLES", "4-SAN BERNARDO", "4-BILBAO", "4-ALONSO MARTINEZ", "4-COLON", "4-SERRANO", "4-VELAZQUEZ", "4-GOYA", "4-LISTA", "4-DIEGO DE LEON", "4-AVDA DE AMERICA", "4-PROSPERIDAD", "4-ALFONSO XIII", "4-AVDA DE LA PAZ", "4-ARTURO SORIA", "4-ESPERANZA", "4-CANILLAS", "4-MAR DE CRISTAL", "4-SAN LORENZO", "4-PARQUE DE SANTA MARIA", "4-HORTALEZA", "4-MANOTERAS", "4-PINAR DE CHAMARTIN"
            ],
            "Línea 5": [
                "5-CASA DE CAMPO", "5-CAMPAMENTO", "5-EMPALME", "5-ALUCHE", "5-EUGENIA DE MONTIJO", "5-CARABANCHEL", "5-VISTA ALEGRE", "5-OPORTO", "5-URGEL", "5-MARQUES DE VADILLO", "5-PIRAMIDES", "5-ACACIAS", "5-PUERTA DE TOLEDO", "5-LA LATINA", "5-OPERA", "5-CALLAO", "5-GRAN VIA", "5-CHUECA", "5-ALONSO MARTINEZ", "5-RUBEN DARIO", "5-NUÑEZ DE BALBOA", "5-DIEGO DE LEON", "5-VENTAS", "5-EL CARMEN", "5-QUINTANA", "5-PUEBLO NUEVO", "5-CIUDAD LINEAL", "5-SUANZES", "5-TORRE ARIAS", "5-CANILLEJAS", "5-EL CAPRICHO", "5-ALAMEDA DE OSUNA"
            ],
            "Línea 6": ["6-LAGUNA", "6-CARPETANA", "6-OPORTO", "6-OPAÑEL ", "6-PLAZA ELIPTICA", "6-USERA", "6-LEGAZPI", "6-ARGANZUELA PLANETARIO", "6-MENDEZ ALVARO", "6-PACIFICO", "6-CONDE DE CASAL", "6-SAINZ DE BARANDA", "6-O´DONNELL", "6-MANUEL BECERRA", "6-DIEGO DE LEON", "6-AVDA DE AMERICA", "6-REPUBLICA ARGENTINA", "6-NUEVOS MINISTERIOS", "6-CUATRO CAMINOS", "6-GUZMAN EL BUENO", "6-VICENTE ALEIXANDRE", "6-CIUDAD UNIVERSITARIA", "6-MONCLOA", "6-ARGUELLES", "6-PRINCIPE PIO", "6-PUERTA DEL ANGEL", "6-ALTO DE EXTREMADURA", "6-LUCERO"],
            "Línea 7": ["7-PITIS", "7-ARROYOFRESNO", "7-LACOMA", "7-AVDA DE LA ILUSTRACION", "7-PEÑAGRANDE", "7-ANTONIO MACHADO", "7-VALDEZARZA", "7-FRANCOS RODRIGUEZ", "7-GUZMAN EL BUENO", "7-ISLAS FILIPINAS", "7-CANAL", "7-ALONSO CANO", "7-GREGORIO MARAÑON", "7-AVDA DE AMERICA", "7-CARTAGENA", "7-PARQUE DE LAS AVDAS", "7-BARRIO DE LA CONCEPCION", "7-PUEBLO NUEVO", "7-ASCAO", "7-GARCIA NOBLEJAS", "7-SIMANCAS", "7-SAN BLAS", "7-LAS MUSAS", "7-ESTADIO METROPOLITANO (A)", "7B-ESTADIO METROPOLITANO (B)", "7B-BARRIO DEL PUERTO", "7B-COSLADA CENTRAL", "7B-LA RAMBLA", "7B-SAN FERNANDO", "7B-JARAMA", "7B-HENARES", "7B-HOSPITAL DE HENARES"],
            "Línea 8": [
                "8-NUEVOS MINISTERIOS", "8-COLOMBIA", "8-PINAR DEL REY", "8-MAR DE CRISTAL", "8-FERIA DE MADRID", "8-AEROPUERTO T1- T2-T3", "8-BARAJAS", "8-AEROPUERTO T4"
            ],
            "Línea 9": ["9-PACO DE LUCIA", "9-MIRASIERRA", "9-HERRERA ORIA", "9-BARRIO DEL PILAR", "9-VENTILLA", "9-PLAZA DE CASTILLA", "9-DUQUE DE PASTRANA", "9-PIO XII", "9-CONCHA ESPINA", "9-CRUZ DEL RAYO", "9-AVDA DE AMERICA", "9-NUÑEZ DE BALBOA", "9-PRINCIPE DE VERGARA", "9-IBIZA", "9-SAINZ DE BARANDA", "9-ESTRELLA", "9-VINATEROS", "9-ARTILLEROS", "9-PAVONES", "9-VALDEBERNARDO", "9-VICALVARO", "9-SAN CIPRIANO", "9-PUERTA DE ARGANDA (A)", "9B-PUERTA DE ARGANDA (B)", "9B-RIVAS-URBANIZACIONES", "9B-RIVAS FUTURA", "9B-RIVAS VACIAMADRID", "9B-LA POVEDA", "9B-ARGANDA DE REY"],
            "Línea 10": ["10-PUERTA DE SUR", "10-JOAQUIN VILUMBRALES", "10-CUATRO VIENTOS", "10-AVIACION ESPAÑOLA", "10-COLONIA JARDIN", "10-CASA DE CAMPO", "10-BATAN", "10-LAGO", "10-PRINCIPE PIO", "10-PLAZA ESPAÑA", "10-TRIBUNAL", "10-ALONSO MARTINEZ", "10-GREGORIO MARAÑON", "10-NUEVOS MINISTERIOS", "10-SANTIAGO BERNABEU", "10-CUZCO", "10-PLAZA DE CASTILLA", "10-CHAMARTIN", "10-BEGOÑA", "10-FUENCARRAL", "10-TRES OLIVOS (A)", "10B-TRES OLIVOS (B)", "10B-MONTECARMELO", "10B-LAS TABLAS", "10B-RONDA DE LA COMUNICACIÓN", "10B-LA GRANJA", "10B-LA MORALEJA", "10B-MARQUES DE VALDAVIA", "10B-MANUEL DE FALLA", "10B-BAUNATAL", "10B-REYES CATOLICOS", "10B-HOSPITAL INFANTA SOFIA"],
            "Línea 11": ["11-PLAZA ELIPTICA", "11-ABRANTES", "11-PAN BENDITO", "11-SAN FRANCISCO", "11-CARABANCHEL ALTO", "11-LA PESETA", "11-LA FORTUNA"],
            "Línea 12": ["12-LORANCA", "12-MALASAÑA", "12-HOSPITAL DE MOSTOLES", "12-PRADILLO", "12-MOSTOLES CENTRAL", "12-UNIV REY J CARLOS", "12-PARQUE OESTE", "12-ALCORCON CENTRAL", "12-PARQUE LISBOA", "12-PUERTA DEL SUR", "12-SAN NICASIO", "12-LEGANES CENTRAL", "12-HOSPITAL SEVERO OCHOA", "12-CASA DEL RELOJ", "12-JULIAN BESTEIRO", "12-EL CARRASCAL", "12-EL BERCIAL", "12-LOS ESPARTALES", "12-EL CASAR", "12-JUAN DE LA CIERVA", "12-GETAFE CENTRAL", "12-ALONSO DE MENDOZA", "12-CONSERVATORIO", "12-ARROYO CULEBRO", "12-PARQUE DE LOS ESTADOS", "12-FUENLABRADA CENTRAL", "12-PARQUE EUROPA", "12-HOSPITAL DE FUENLABRADA"],
            "Línea ML": ["ML-PINAR DE CHAMARTIN", "ML-FUENTE DE LA MORA", "ML-VIRGEN DEL CORTIJO", "ML-ANTONIO SAURA", "ML-ALVAREZ DE VILLAAMIL", "ML-BLASCO IBAÑEZ", "ML-MARIA TUDOR", "ML-PALAS DEL REYLAS ", "ML-LAS TABLAS"],
            "Línea R": ["R-PRINCIPE PIO", "R-OPERA"],
            "DEPOSITOS": ["1-DEPOSITO 9 z1 (HORTALEZA)", "1-DEPOSITO 12 (VALDECARROS)", "2-DEPOSITO 2 (VENTAS)", "3-DEPOSITO 13 (VILLAVERDE)", "4-DEPOSITO 9 z4 (HORTALEZA)", "5-DEPOSITO 4 z5 (CANILLEJAS)", "5-DEPOSITO 5 (ALUCHE)", "6-DEPOSITO 8(LAGUNA)", "7-DEPOSITO 4 (CANILLEJAS) (7A)", "7-DEPOSITO 4 (CANILLEJAS) (7B)", "8-DEPOSITO 6 (FUENCARRAL)", "9-COCHERAS PTA. ARGANDA (9A)", "9B-COCHERAS PTA. ARGANDA (9B)", "9-DEPOSITO 7 (SACEDAL)", "10-DEPOSITO 10 (CUATRO VIENTOS)", "10-DEPOSITO 6 (FUENCARRAL)(10A)", "10-DEPOSITO 6 (FUENCARRAL)(10B)", "11-DEPOSITO 10 (CUATRO VIENTOS)", "12-DEPOSITO 11 (LORANCA)", "ML-DEPOSITO 9 ZML (HORTALEZA)"]
        }


# Correspondence between stations on different lines
CORRESPONDENCIAS = {
    "1-PINAR DE CHAMARTIN": ["4-PINAR DE CHAMARTIN", "ML-PINAR DE CHAMARTIN"],
    "4-PINAR DE CHAMARTIN": ["1-PINAR DE CHAMARTIN", "ML-PINAR DE CHAMARTIN"],
    "ML-PINAR DE CHAMARTIN": ["1-PINAR DE CHAMARTIN", "4-PINAR DE CHAMARTIN"],
    "1-CHAMARTIN": ["10-CHAMARTIN"],
    "10-CHAMARTIN": ["1-CHAMARTIN"],
    "1-PLAZA DE CASTILLA": ["9-PLAZA DE CASTILLA", "10-PLAZA DE CASTILLA"],
    "9-PLAZA DE CASTILLA": ["1-PLAZA DE CASTILLA", "10-PLAZA DE CASTILLA"],
    "10-PLAZA DE CASTILLA": ["1-PLAZA DE CASTILLA", "9-PLAZA DE CASTILLA"],
    "1-CUATRO CAMINOS": ["2-CUATRO CAMINOS", "6-CUATRO CAMINOS"],
    "2-CUATRO CAMINOS": ["1-CUATRO CAMINOS", "6-CUATRO CAMINOS"],
    "6-CUATRO CAMINOS": ["1-CUATRO CAMINOS", "2-CUATRO CAMINOS"],
    "1-BILBAO": ["4-BILBAO"],
    "4-BILBAO": ["1-BILBAO"],
    "1-TRIBUNAL": ["10-TRIBUNAL"],
    "10-TRIBUNAL": ["1-TRIBUNAL"],
    "1-GRAN VIA": ["5-GRAN VIA"],
    "5-GRAN VIA": ["1-GRAN VIA"],
    "1-SOL": ["2-SOL", "3-SOL"],
    "2-SOL": ["1-SOL", "3-SOL"],
    "3-SOL": ["1-SOL", "2-SOL"],
    "1-PACIFICO": ["6-PACIFICO"],
    "6-PACIFICO": ["1-PACIFICO"],
    "2-VENTAS": ["5-VENTAS"],
    "5-VENTAS": ["2-VENTAS"],
    "2-MANUEL BECERRA": ["6-MANUEL BECERRA"],
    "6-MANUEL BECERRA": ["2-MANUEL BECERRA"],
    "2-GOYA": ["4-GOYA"],
    "4-GOYA": ["2-GOYA"],
    "2-PRINCIPE DE VERGARA": ["9-PRINCIPE DE VERGARA"],
    "9-PRINCIPE DE VERGARA": ["2-PRINCIPE DE VERGARA"],
    "2-OPERA": ["5-OPERA", "R-OPERA"],
    "5-OPERA": ["2-OPERA", "R-OPERA"],
    "R-OPERA": ["2-OPERA", "5-OPERA"],
    "2-SAN BERNARDO": ["4-SAN BERNARDO"],
    "4-SAN BERNARDO": ["2-SAN BERNARDO"],
    "2-CANAL": ["7-CANAL"],
    "7-CANAL": ["2-CANAL"],
    "3-EL CASAR": ["12-EL CASAR"],
    "12-EL CASAR": ["3-EL CASAR"],
    "3-LEGAZPI": ["6-LEGAZPI"],
    "6-LEGAZPI": ["3-LEGAZPI"],
    "3-EMBAJADORES": ["5-ACACIAS"],
    "5-ACACIAS": ["3-EMBAJADORES"],
    "3-CALLAO": ["5-CALLAO"],
    "5-CALLAO": ["3-CALLAO"],
    "3-PLAZA ESPAÑA": ["10-PLAZA ESPAÑA", "2-NOVICIADO"],
    "10-PLAZA ESPAÑA": ["3-PLAZA ESPAÑA", "2-NOVICIADO"],
    "2-NOVICIADO": ["3-PLAZA ESPAÑA", "10-PLAZA ESPAÑA"],
    "3-ARGUELLES": ["4-ARGUELLES", "6-ARGUELLES"],
    "4-ARGUELLES": ["3-ARGUELLES", "6-ARGUELLES"],
    "6-ARGUELLES": ["3-ARGUELLES", "4-ARGUELLES"],
    "3-MONCLOA": ["6-MONCLOA"],
    "6-MONCLOA": ["3-MONCLOA"],
    "4-ALONSO MARTINEZ": ["5-ALONSO MARTINEZ", "10-ALONSO MARTINEZ"],
    "5-ALONSO MARTINEZ": ["4-ALONSO MARTINEZ", "10-ALONSO MARTINEZ"],
    "10-ALONSO MARTINEZ": ["4-ALONSO MARTINEZ", "5-ALONSO MARTINEZ"],
    "4-DIEGO DE LEON": ["5-DIEGO DE LEON", "6-DIEGO DE LEON"],
    "5-DIEGO DE LEON": ["4-DIEGO DE LEON", "6-DIEGO DE LEON"],
    "6-DIEGO DE LEON": ["4-DIEGO DE LEON", "5-DIEGO DE LEON"],
    "4-AVDA DE AMERICA": ["6-AVDA DE AMERICA", "7-AVDA DE AMERICA", "9-AVDA DE AMERICA"],
    "6-AVDA DE AMERICA": ["4-AVDA DE AMERICA", "7-AVDA DE AMERICA", "9-AVDA DE AMERICA"],
    "7-AVDA DE AMERICA": ["4-AVDA DE AMERICA", "6-AVDA DE AMERICA", "9-AVDA DE AMERICA"],
    "9-AVDA DE AMERICA": ["4-AVDA DE AMERICA", "6-AVDA DE AMERICA", "7-AVDA DE AMERICA"],
    "4-MAR DE CRISTAL": ["8-MAR DE CRISTAL"],
    "8-MAR DE CRISTAL": ["4-MAR DE CRISTAL"],
    "5-PUEBLO NUEVO": ["7-PUEBLO NUEVO"],
    "7-PUEBLO NUEVO": ["5-PUEBLO NUEVO"],
    "7-GREGORIO MARAÑON": ["10-GREGORIO MARAÑON"],
    "5-NUÑEZ DE BALBOA": ["9-NUÑEZ DE BALBOA"],
    "9-NUÑEZ DE BALBOA": ["5-NUÑEZ DE BALBOA"],
    "5-OPORTO": ["6-OPORTO"],
    "6-OPORTO": ["5-OPORTO"],
    "5-CASA DE CAMPO": ["10-CASA DE CAMPO"],
    "10-CASA DE CAMPO": ["5-CASA DE CAMPO"],
    "6-PLAZA ELIPTICA": ["11-PLAZA ELIPTICA"],
    "11-PLAZA ELIPTICA": ["6-PLAZA ELIPTICA"],
    "6-SAINZ DE BARANDA": ["9-SAINZ DE BARANDA"],
    "9-SAINZ DE BARANDA": ["6-SAINZ DE BARANDA"],
    "6-NUEVOS MINISTERIOS": ["8-NUEVOS MINISTERIOS", "10-NUEVOS MINISTERIOS"],
    "8-NUEVOS MINISTERIOS": ["6-NUEVOS MINISTERIOS", "10-NUEVOS MINISTERIOS"],
    "10-NUEVOS MINISTERIOS": ["6-NUEVOS MINISTERIOS", "8-NUEVOS MINISTERIOS"],
    "6-GUZMAN EL BUENO": ["7-GUZMAN EL BUENO"],
    "7-GUZMAN EL BUENO": ["6-GUZMAN EL BUENO"],
    "6-PRINCIPE PIO": ["10-PRINCIPE PIO", "R-PRINCIPE PIO"],
    "10-PRINCIPE PIO": ["6-PRINCIPE PIO", "R-PRINCIPE PIO"],
    "R-PRINCIPE PIO": ["6-PRINCIPE PIO", "10-PRINCIPE PIO"],
    "8-COLOMBIA": ["9-COLOMBIA"],
    "9-COLOMBIA": ["8-COLOMBIA"],
    "10-PUERTA DE SUR": ["12-PUERTA DEL SUR"],
    "12-PUERTA DEL SUR": ["10-PUERTA DE SUR"],
    "10B-LAS TABLAS": ["ML-LAS TABLAS"],
    "ML-LAS TABLAS": ["10B-LAS TABLAS"]
}

# Correspondence depositos
CORRESPONDENCIAS_DEPOSITOS = {
    "1-DEPOSITO 9 z1 (HORTALEZA)": ["4-DEPOSITO 9 z4 (HORTALEZA)", "ML-DEPOSITO 9 ZML (HORTALEZA)"],
    "4-DEPOSITO 9 z4 (HORTALEZA)": ["1-DEPOSITO 9 z1 (HORTALEZA)", "ML-DEPOSITO 9 ZML (HORTALEZA)"],
    "ML-DEPOSITO 9 ZML (HORTALEZA)": ["1-DEPOSITO 9 z1 (HORTALEZA)", "4-DEPOSITO 9 z4 (HORTALEZA)"],
    "5-DEPOSITO 4 z5 (CANILLEJAS)": ["7-DEPOSITO 4 (CANILLEJAS) (7A)", "7-DEPOSITO 4 (CANILLEJAS) (7B)"],
    "7-DEPOSITO 4 (CANILLEJAS) (7A)": ["5-DEPOSITO 4 z5 (CANILLEJAS)", "7-DEPOSITO 4 (CANILLEJAS) (7B)"],
    "7-DEPOSITO 4 (CANILLEJAS) (7B)": ["5-DEPOSITO 4 z5 (CANILLEJAS)", "7-DEPOSITO 4 (CANILLEJAS) (7A)"],
    "9-COCHERAS PTA. ARGANDA (9A)": ["9B-COCHERAS PTA. ARGANDA (9B)"],
    "9B-COCHERAS PTA. ARGANDA (9B)": ["9-COCHERAS PTA. ARGANDA (9A)"],
    "10-DEPOSITO 6 (FUENCARRAL)(10A)": ["10-DEPOSITO 6 (FUENCARRAL)(10B)"],
    "10-DEPOSITO 6 (FUENCARRAL)(10B)": ["10-DEPOSITO 6 (FUENCARRAL)(10A)"]
}

# Special step exceptions between pairs of stations
# Keys must be normalized names: use normalize() in the main code
EXCEPCIONES = {
    (normalize("7-DEPOSITO 4 (CANILLEJAS) (7A)"), normalize("7-LAS MUSAS")): 2,
    (normalize("5-DEPOSITO 4 z5 (CANILLEJAS)"), normalize("5-CANILLEJAS")): 2,
    (normalize("10-DEPOSITO 6 (FUENCARRAL)(10A)"), normalize("10-TRES OLIVOS (A)")): 2,
    (normalize("10-DEPOSITO 6 (FUENCARRAL)(10B)"), normalize("10B-TRES OLIVOS (B)")): 2,
    (normalize("9-DEPOSITO 7 (SACEDAL)"), normalize("9-MIRASIERRA")): 3,
    (normalize("6-DEPOSITO 8(LAGUNA)"), normalize("6-LAGUNA")): 3,
    (normalize("9-COCHERAS PTA. ARGANDA (9A)"), normalize("9-PUERTA DE ARGANDA (A)")): 3,
    (normalize("9B-COCHERAS PTA. ARGANDA (9B)"), normalize("9B-PUERTA DE ARGANDA (B)")): 3,
    (normalize("1-DEPOSITO 9 z1 (HORTALEZA)"), normalize("1-PINAR DE CHAMARTIN")): 3,
    (normalize("4-DEPOSITO 9 z4 (HORTALEZA)"), normalize("4-PINAR DE CHAMARTIN")): 3,
    (normalize("10-DEPOSITO 10 (CUATRO VIENTOS)"), normalize("10-CUATRO VIENTOS")): 2,
    (normalize("10-CUATRO VIENTOS"), normalize("10-DEPOSITO 10 (CUATRO VIENTOS)")): 2,
    (normalize("12-DEPOSITO 11 (LORANCA)"), normalize("12-LORANCA")): 2,
    (normalize("1-DEPOSITO 12 (VALDECARROS)"), normalize("1-VALDECARROS")): 3,
    (normalize("3-DEPOSITO 13 (VILLAVERDE)"), normalize("3-VILLAVERDE ALTO")): 3
    }

EXCEPCIONES2 = {
    (normalize("4-DIEGO DE LEON"), normalize("5-DIEGO DE LEON")): 3,
    (normalize("4-DIEGO DE LEON"), normalize("6-DIEGO DE LEON")): 3,
    (normalize("5-DIEGO DE LEON"), normalize("6-DIEGO DE LEON")): 2,
    (normalize("5-NUÑEZ DE BALBOA"), normalize("9-NUÑEZ DE BALBOA")): 3,
    (normalize("5-ACACIAS"), normalize("3-EMBAJADORES")): 3,
    (normalize("2-NOVICIADO"), normalize("3-PLAZA ESPAÑA")): 3,
    (normalize("2-NOVICIADO"), normalize("10-PLAZA ESPAÑA")): 3,
    (normalize("6-NUEVOS MINISTERIOS"), normalize("8-NUEVOS MINISTERIOS")): 3,
    (normalize("6-NUEVOS MINISTERIOS"), normalize("10-NUEVOS MINISTERIOS")): 3,
    (normalize("6-PLAZA ELIPTICA"), normalize("11-PLAZA ELIPTICA")): 2,
    (normalize("1-TRIBUNAL"), normalize("10-TRIBUNAL")): 2,
    (normalize("4-ALONSO MARTINEZ"), normalize("10-ALONSO MARTINEZ")): 2
    # ... otras excepciones que no se aplicaban correctamente
}

# Mapeo de depósitos a su estación "principal" asociada.
# Sólo estos depósitos tendrán coste 0 al pasar por ellos.
DEPOSITOS_ASOCIACIONES = {
    "1-DEPOSITO 9 z1 (HORTALEZA)": "1-PINAR DE CHAMARTIN", 
    "1-DEPOSITO 12 (VALDECARROS)": "1-VALDECARROS",
    "2-DEPOSITO 2 (VENTAS)": "2-VENTAS", 
    "3-DEPOSITO 13 (VILLAVERDE)": "3-VILLAVERDE ALTO", 
    "4-DEPOSITO 9 z4 (HORTALEZA)": "4-PINAR DE CHAMARTIN", 
    "5-DEPOSITO 4 z5 (CANILLEJAS)": "5-CANILLEJAS", 
    "5-DEPOSITO 5 (ALUCHE)": "5-ALUCHE", 
    "6-DEPOSITO 8(LAGUNA)": "6-LAGUNA", 
    "7-DEPOSITO 4 (CANILLEJAS) (7A)": "7-LAS MUSAS", 
    "7-DEPOSITO 4 (CANILLEJAS) (7B)": "7-LAS MUSAS", 
    "9-COCHERAS PTA. ARGANDA (9A)": "9-PUERTA DE ARGANDA (A)", 
    "9B-COCHERAS PTA. ARGANDA (9B)": "9B-PUERTA DE ARGANDA (B)", 
    "9-DEPOSITO 7 (SACEDAL)": "9-MIRASIERRA", 
    "10-DEPOSITO 10 (CUATRO VIENTOS)": "10-CUATRO VIENTOS", 
    "10-DEPOSITO 6 (FUENCARRAL)(10A)": "10-TRES OLIVOS (A)", 
    "10-DEPOSITO 6 (FUENCARRAL)(10B)": "10B-TRES OLIVOS (B)", 
    "11-DEPOSITO 10 (CUATRO VIENTOS)": "11-LA FORTUNA", 
    "12-DEPOSITO 11 (LORANCA)": "12-LORANCA", 
    "ML-DEPOSITO 9 ZML (HORTALEZA)": "ML-PINAR DE CHAMARTIN"

    # Añade aquí cada depósito y su estación asociada:
    # "<DEPÓSITO>": "<ESTACIÓN_ASOCIADA>",
}
# --- Estaciones cabecera destacadas ---
CABECERAS = [
    "1-PINAR DE CHAMARTIN", "1-VALDECARROS", "1-MIGUEL HERNANDEZ",
    "2-LAS ROSAS", "2-CUATRO CAMINOS",
    "3-EL CASAR", "3-MONCLOA",
    "4-PINAR DE CHAMARTIN", "4-ARGUELLES",
    "5-ALAMEDA DE OSUNA", "5-CASA DE CAMPO",
    "6-LAGUNA", "6-CIUDAD UNIVERSITARIA",
    "7-PITIS", "7-ESTADIO METROPOLITANO (A)", "7B-ESTADIO METROPOLITANO (B)", "7B-HOSPITAL DE HENARES",
    "8-AEROPUERTO T4", "8-NUEVOS MINISTERIOS",
    "9-PACO DE LUCIA", "9-PUERTA DE ARGANDA (A)", "9B-PUERTA DE ARGANDA (B)", "9B-ARGANDA DE REY",
    "10-PUERTA DE SUR", "10-TRES OLIVOS (A)", "10B-TRES OLIVOS (B)", "10B-HOSPITAL INFANTA SOFIA",
    "11-PLAZA ELIPTICA", "11-LA FORTUNA",
    "12-LORANCA", "12-UNIV REY J CARLOS",
    "ML-PINAR DE CHAMARTIN", "ML-LAS TABLAS",
    "R-PRINCIPE PIO"
]

# --- Estaciones depósito destacadas (resaltar en negrita) ---
DEPOSITOS = [
    "1-DEPOSITO 9 z1 (HORTALEZA)", "1-DEPOSITO 12 (VALDECARROS)",
    "2-DEPOSITO 2 (VENTAS)", 
    "3-DEPOSITO 13 (VILLAVERDE)", 
    "4-DEPOSITO 9 z4 (HORTALEZA)", 
    "5-DEPOSITO 4 z5 (CANILLEJAS)", "5-DEPOSITO 5 (ALUCHE)", 
    "6-DEPOSITO 8(LAGUNA)", 
    "7-DEPOSITO 4 (CANILLEJAS) (7A)", "7-DEPOSITO 4 (CANILLEJAS) (7B)", 
    "8-DEPOSITO 6 (FUENCARRAL)", 
    "9-COCHERAS PTA. ARGANDA (9A)", "9B-COCHERAS PTA. ARGANDA (9B)", "9-DEPOSITO 7 (SACEDAL)", 
    "10-DEPOSITO 10 (CUATRO VIENTOS)", "10-DEPOSITO 6 (FUENCARRAL)(10A)", "10-DEPOSITO 6 (FUENCARRAL)(10B)", 
    "11-DEPOSITO 10 (CUATRO VIENTOS)", 
    "12-DEPOSITO 11 (LORANCA)", 
    "ML-DEPOSITO 9 ZML (HORTALEZA)"
]

# --- orden de lineas al ordenar a igual de pasos ---
ORDEN_LINEAS = {
    "1": 1,
    "2": 2,
    "R": 3,
    "3": 4,
    "4": 5,
    "5": 6,
    "6": 7,
    "7B": 8,
    "7": 9,
    "8": 10,
    "9B": 11,
    "9": 12,
    "10B": 13,
    "10": 14,
    "11": 15,
    "12": 16,
    "ML": 17
}
